name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # JOB 1: TESTE (O Porteiro)
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Cypress run 🧪
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: 'http://localhost:5173/fallout/'
          browser: chrome
      
      # ADICIONE AQUI: Logo após o Cypress e ANTES do próximo Job
      - name: Upload Cypress Artifacts 📸
        if: failure() 
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots-and-videos
          path: |
            cypress/screenshots
            cypress/videos
          retention-days: 7

  # JOB 2: DEPLOY (O que publica)
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/
      - name: Deploy
        uses: actions/deploy-pages@v4